#!/usr/bin/env python3
# latest file

import argparse, socket, time, json, select, struct, sys, math

ENCODING = "ascii"

MSG_SIZE = 1500
TIMEOUT = 30

##########################################################################

# Message Fields
SEQN = "sequence"
DATA = "data"
ACK = "ack"
SACK = "sack"
EOF = "eof"

##########################################################################

TEARDOWN_ACKS = 5

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.remote_host, self.remote_port))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()
    def process_received_packets(self):
        sorted_packets = sorted(self.received_packets, key=lambda packet: packet[SEQN])
        for packet in sorted_packets:
           if packet[SEQN] == self.read_data:
              sys.stdout.write(packet[DATA])
              self.read_data = packet[SEQN] + len(packet[DATA])
        self.received_packets = list(filter(lambda packet: packet[SEQN] > self.read_data, sorted_packets))
    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                data, addr = conn.recvfrom(65535)

                # Grab the remote host/port if we don't alreadt have it
                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]

                msg = json.loads(data.decode('utf-8'))
                self.log("Received data message %s" % msg)

                # Print out the data to stdout
                print(msg["data"], end='', flush=True)

                # Always send back an ack
                self.send({ "type": "ack" })


        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
